apiVersion: v1
kind: Pod
metadata:
  name: angularank
spec:
  containers:
    - name: app
      image: gcr.io/my-bio-163107/angularank
      imagePullPolicy: Always
      env:
        - name: TODO_KEY
          value: ${TODO_KEY}
      ports:
        - containerPort: 3000
          hostPort: 80

